server:
  port: 8080

app:
  jwt:
    secret: field-mapper-secret-key-must-be-at-least-256-bits-long-12345678
    expiration: 86400000
  business-datasource: melone
  datasources:
    pg-local:
      type: postgresql
      host: localhost
      port: 5432
      database: postgres
      schema: public
      username: postgres
      password: postgres

    oracle-local:
      type: oracle
      host: localhost
      port: 1521
      database: FREEPDB1
      schema: HISSAAS
      username: HISSAAS
      password: hissaas123

    melone:
      type: oracle
      host: localhost
      port: 1521
      database: FREEPDB1
      schema: MELONE
      username: melone
      password: melone123

    oracle-cdb:
      type: oracle
      host: localhost
      port: 1521
      database: FREE
      schema: SYSTEM
      username: sys
      password: oracle123
      sysdba: true

export:
  output-dir: ${java.io.tmpdir}/field-mapper-exports
