server:
  port: 8080

app:
  jwt:
    secret: field-mapper-secret-key-must-be-at-least-256-bits-long-12345678
    expiration: 86400000
  business-datasource: melone
  datasources:
    pg-local:
      type: postgresql
      host: localhost
      port: 5432
      database: postgres
      schema: public
      username: postgres
      password: postgres

    melone:
      type: oracle
      host: localhost
      port: 1521
      database: FREEPDB1
      schema: MELONE
      username: melone
      password: melone123


export:
  output-dir: ${java.io.tmpdir}/field-mapper-exports
